import { Text3D } from "@react-three/drei"
import { Canvas } from "@react-three/fiber"
import Head from "next/head"
import Image from "next/image"
import { Suspense } from "react"
import SkyBackground from "../components/SkyBackground"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.canvas}>
        <Canvas
          gl={{ antialias: false, powerPreference: "high-performance" }}
          style={{ height: "100vh!important", width: "100vw!important" }}
        >
          <Suspense fallback={null}>
            <Text3D font={"./opensans.json"} position={[-5, 0, 0]}>
              @sharathkrml
              <meshNormalMaterial />
            </Text3D>
            {/* <SkyBackground /> */}
          </Suspense>
        </Canvas>
      </div>
      <main className={styles.main}>
        <h1>
          Occaecat proident et esse sint nulla quis nisi magna laborum Lorem sit
          duis.
        </h1>
      </main>
    </div>
  )
}
